# Pytorch Basic Operations

The **Tensor** is a fundamental structure in PyTorch which is very similar to an array or matrix. Tensors are used to encode the inputs and outputs of a model, as well as the model’s parameters. In this exercise, you will learn how to implement basic tensor operations.

In [2]:
"""
ONLY COMPLETE METHODS AND CLASSES MARKED "TODO".
DO NOT IMPORT ADDITIONAL LIBRARIES.
"""
import torch

For some of the exercises, the documentation of `torch.Tensor` should be very helpful:
https://pytorch.org/docs/stable/tensors.html

Basically, when you see an unfamiliar function, you should check in the documentation to see what the **input/output** of the function should look like, what **parameters** are needed and how these parameters will affect the result. 

## Create Tensors

In [3]:
# Create tensors
shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)
z = torch.zeros(shape)

## Addition
Implement a simple tensor addition x + y and assign the result to z. 

In [4]:
"""
TODO: Implement a simple tensor addition x + y. 
Assign the result to z. 
"""
z = x + y

print("x = :")
print(x)
print("y = :")
print(y)

print("\n")

print("x + y = :")
print(z)
print("\n")

x = :
tensor([[0.2360, 0.7560, 0.1999],
        [0.7992, 0.5886, 0.8820]])
y = :
tensor([[0.7853, 0.1520, 0.9190],
        [0.4666, 0.0645, 0.8494]])


x + y = :
tensor([[1.0213, 0.9080, 1.1189],
        [1.2658, 0.6531, 1.7314]])




## Reshape
Reshape the tensor **z** into the specified shape (new_shape)

In [5]:
z = torch.rand([2,3])
new_shape = (3,2)

"""
TODO: Reshapes the tensor z with the given shape (new_shape) 
Hint: use view()
"""
z = z.view(new_shape)

print("z and its shape after reshaping:")
print(z)
print(z.shape)
print("\n")

z and its shape after reshaping:
tensor([[0.0977, 0.4753],
        [0.4123, 0.2694],
        [0.4455, 0.3110]])
torch.Size([3, 2])




## Flatten
Flatten the tensor **z**.

In [6]:
z = torch.rand([2,3])
"""
Flatten
TODO: Flatten the tensor z.
Hint: use view()
"""

#z = torch.flatten(z)
z = z.view(-1)

# you can also use z = torch.flatten(z) in case z is not contiguous.

print("z and its shape after the flatten operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the flatten operation:
tensor([0.3598, 0.0817, 0.2227, 0.4138, 0.2769, 0.6032])
torch.Size([6])




## Transpose
Swap the first dimension and the second dimension of **z**.

In [7]:
z = torch.rand([2,3])
print(z)
"""
TODO: Swaps the first dimension and the second dimension of z.
"""
z = torch.transpose(z, 0, 1)


print("z and its shape after the transpose operation:")
print(z)
print(z.shape)
print("\n")

tensor([[0.2141, 0.1077, 0.8888],
        [0.2834, 0.7487, 0.0073]])
z and its shape after the transpose operation:
tensor([[0.2141, 0.2834],
        [0.1077, 0.7487],
        [0.8888, 0.0073]])
torch.Size([3, 2])




## Permutation
Permute the dimensions of **z** according to the specified order (exchanging axes).

In [8]:
"""
Permutation
TODO: Permute the dimensions of z according to the given order (swapping axes).
torch.permute(input, dims)
"""

# Create a new tensor
shape = (3,5,1)
z = torch.rand(shape)
order = [2,0,1]

z = torch.permute(z, order)

print("z and its shape after permutation")
print(z)
print(z.shape)
print("\n")

z and its shape after permutation
tensor([[[0.9057, 0.5339, 0.9899, 0.9080, 0.7272],
         [0.2836, 0.2157, 0.2554, 0.4408, 0.8950],
         [0.1230, 0.9053, 0.6458, 0.6690, 0.3103]]])
torch.Size([1, 3, 5])




## Dot Product
Calculate the dot product of two rank 1 tensors (vectors) u and v.

In [9]:
"""
TODO: Calculate the dot product of
      two rank 1 tensors (vectors) u and v.
"""


# Create two vectors
v = torch.tensor([2, 3])
u = torch.tensor([2, 1])

result = torch.dot(u, v)

print("The dot product of u and v:")
print(result.item())
print("\n")

The dot product of u and v:
7




## Concatenation

In [10]:
shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)

"""
TODO: Concatenate (x,y) in dimension 1.
torch.cat((x, y), dim)
"""
z = torch.cat((x,y), 1)

print("The Concatenated tensor z of (x, y)")
print(z)
print("\n")

The Concatenated tensor z of (x, y)
tensor([[0.0999, 0.1070, 0.9263, 0.2139, 0.4824, 0.8240],
        [0.5979, 0.8230, 0.4661, 0.4143, 0.7949, 0.5283]])


